# Generated by Django 4.2.2 on 2023-06-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_about_dealer_profile_slug_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
