# Generated by Django 4.2.2 on 2023-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_creditsession_delete_profilecredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsession',
            name='reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
