# Generated by Django 4.2.2 on 2023-07-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_creditsession_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsession',
            name='session_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
