# Generated by Django 4.2.2 on 2023-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_creditsession_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='credithistory',
            name='session_des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credithistory',
            name='session_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditsession',
            name='session_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
