# Generated by Django 4.2.2 on 2023-07-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_credithistory_session_des_credithistory_session_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsession',
            name='is_Neutral',
            field=models.BooleanField(default=False),
        ),
    ]
