# Generated by Django 4.2.2 on 2023-07-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_creditsession_is_neutral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditsession',
            old_name='is_Neutral',
            new_name='is_neutral',
        ),
    ]
