# Generated by Django 4.2.2 on 2023-07-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_credithistory_slug_creditsession_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='credithistory',
            name='is_neutral',
            field=models.BooleanField(default=False),
        ),
    ]
