# Generated by Django 4.2.2 on 2023-07-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_credithistory_is_neutral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='creditsession',
            name='session_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='creditsession',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.achievement'),
        ),
    ]
