# Generated by Django 4.2.2 on 2023-07-29 08:25

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_achievement_image_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='credit_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_path),
        ),
    ]
