# Generated by Django 4.2.2 on 2023-06-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_market_long_description'),
        ('carts', '0003_alter_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.market'),
        ),
    ]
