# Generated by Django 4.2.2 on 2023-07-21 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0007_rename_number_of_buyer_market_quantity_left'),
        ('carts', '0005_alter_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_dealed', models.DateTimeField(blank=True, null=True)),
                ('in_session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.market')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
