# Generated by Django 4.2.2 on 2023-07-22 09:15

import carts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitemhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=carts.models.upload_path),
        ),
        migrations.AddField(
            model_name='cartitemhistory',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=carts.models.upload_path_history),
        ),
    ]
