# Generated by Django 4.2.2 on 2023-07-22 09:18

import carts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cart_qrcode_cartitemhistory_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=carts.models.upload_path),
        ),
    ]
