# Generated by Django 4.2.2 on 2023-06-18 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('price_per_unit', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('solar', 'Solar Energy'), ('Biof', 'Biofuel'), ('water', 'Water Sources'), ('forest', 'Forest')], max_length=100)),
                ('number_of_buyer', models.PositiveIntegerField(blank=True, null=True)),
                ('deal_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
