# Generated by Django 4.2.2 on 2023-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
