# Generated by Django 4.2.2 on 2023-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_market_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
