# Generated by Django 4.2.2 on 2023-06-20 13:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_market_image_alter_market_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
