# Generated by Django 4.2.2 on 2023-07-20 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_alter_market_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
