# Generated by Django 4.2.2 on 2023-07-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_market_dealer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='number_of_buyer',
            new_name='quantity_left',
        ),
    ]
