# Generated by Django 4.2.2 on 2023-07-20 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealer', '0003_dealer_shop_icon_alter_dealer_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
