# Generated by Django 4.2.2 on 2023-06-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deals',
            field=models.ManyToManyField(to='market.market'),
        ),
    ]
