# Generated by Django 4.2.2 on 2023-07-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
