# Generated by Django 4.2.2 on 2023-07-25 12:17

import badges.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0014_rename_is_neutral_creditsession_is_neutral'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeutralBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('badges', models.ImageField(blank=True, null=True, upload_to=badges.models.upload_path)),
                ('in_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='profiles.creditsession')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveNeutralBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('badges', models.ImageField(blank=True, null=True, upload_to=badges.models.upload_path_archive)),
                ('in_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='profiles.credithistory')),
            ],
        ),
    ]
