# Generated by Django 4.2.2 on 2023-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neutralbadges',
            name='is_obtained',
            field=models.BooleanField(default=False),
        ),
    ]
