# Generated by Django 4.2.2 on 2023-07-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_neutralbadges_in_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neutralbadges',
            name='name',
        ),
        migrations.AddField(
            model_name='neutralbadges',
            name='session_namename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
