# Generated by Django 4.2.2 on 2023-07-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_remove_neutralbadges_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neutralbadges',
            old_name='session_namename',
            new_name='session_name',
        ),
    ]
