# Generated by Django 4.2.2 on 2023-07-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_credithistory_slug_creditsession_slug'),
        ('badges', '0005_rename_session_namename_neutralbadges_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neutralbadges',
            name='in_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='badges', to='profiles.creditsession'),
        ),
    ]
