# Generated by Django 4.2.2 on 2023-07-29 07:26

import badges.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_achievement_alter_creditsession_session_name_and_more'),
        ('badges', '0008_alter_neutralbadges_in_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('badges', models.ImageField(blank=True, null=True, upload_to=badges.models.upload_path)),
                ('is_obtained', models.BooleanField(default=False)),
                ('in_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ach_badge', to='profiles.creditsession')),
            ],
        ),
    ]
