# Generated by Django 4.2.2 on 2023-07-29 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_profile_image'),
        ('badges', '0009_achievementbadges'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementbadges',
            name='in_achivement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement', to='profiles.achievement'),
        ),
    ]
