# Generated by Django 4.2.2 on 2023-07-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_profile_image'),
        ('badges', '0010_achievementbadges_in_achivement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementbadges',
            name='in_achivement',
        ),
        migrations.AddField(
            model_name='achievementbadges',
            name='in_achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_achievement', to='profiles.achievement'),
        ),
    ]
