# Generated by Django 4.2.2 on 2023-07-29 15:45

import badges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0011_remove_achievementbadges_in_achivement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementbadges',
            name='badges',
            field=models.ImageField(blank=True, null=True, upload_to=badges.models.ach_upload_path),
        ),
    ]
